[hyperparameters]
num_classes = 4

[path]
result_dir = "../thai/result/20250302T084132"
model_name = "mobilenetv3_small_best_model.pth"
img_path = "../thai/data/mydesk/mydesk_raw/run3/20250228T165549_0011.jpg"

[gpu]
gpu_index = 1